import {
  pgTable,
  bigint,
  varchar,
  text,
  timestamp,
  date,
  index,
  char,
  numeric,
} from "drizzle-orm/pg-core";
import {
  enumZeroOne,
  enumCustomerLevel,
  enumCustomerGender,
  enumBankStatusPajak,
  enumCustomerBisnisType,
  enumCustomerTfSaldo,
  enumCustomerStatus,
} from "./enums";

export const customerTable = pgTable(
  "_customer",
  {
    customerId: bigint("customer_id", { mode: "number" }).generatedAlwaysAsIdentity().primaryKey(),
    customerLevel: enumCustomerLevel("customer_level").notNull(),
    customerParent: bigint("customer_parent", { mode: "number" }).notNull().default(0),
    customerRoot: varchar("customer_root", { length: 50 }).notNull(),
    customerCode: varchar("customer_code", { length: 50 }).notNull(),
    customerRegId: text("customer_reg_id"),
    customerMin: varchar("customer_min", { length: 30 }).default(""),
    customerMdn: varchar("customer_mdn", { length: 15 }).default(""),
    customerMsisdn: varchar("customer_msisdn", { length: 16 }).default(""),
    customerHandset: varchar("customer_handset", { length: 100 }).default(""),
    customerProvider: varchar("customer_provider", { length: 15 }).default(""),
    customerName: varchar("customer_name", { length: 50 }).default(""),
    customerEmail: varchar("customer_email", { length: 100 }).default(""),
    customerPhone: varchar("customer_phone", { length: 20 }).default(""),
    customerWhatsapp: varchar("customer_whatsapp", { length: 20 }).notNull(),
    customerPassword: text("customer_password"),
    customerPasswordTrx: text("customer_password_trx").notNull(),
    customerImage: varchar("customer_image", { length: 100 }).default(""),
    customerBirthPlace: varchar("customer_birth_place", { length: 100 }).default(""),
    customerBirthDate: date("customer_birth_date"),
    customerGender: enumCustomerGender("customer_gender"),
    customerAddress: varchar("customer_address", { length: 250 }).default(""),
    customerCity: varchar("customer_city", { length: 100 }).default(""),
    customerProvince: varchar("customer_province", { length: 50 }).default(""),
    customerPostcode: char("customer_postcode", { length: 5 }).default(""),
    customerSaldoMinus: numeric("customer_saldo_minus", { precision: 10, scale: 2 })
      .notNull()
      .default("0"),
    picId: bigint("pic_id", { mode: "number" }).notNull().default(0),
    customerSmKey: text("customer_sm_key").notNull(),
    customerEmoneyLimit: numeric("customer_emoney_limit", { precision: 10, scale: 2 }).default("0"),
    customerTrxLimit: numeric("customer_trx_limit", { precision: 10, scale: 2 }).default("0"),
    customerTfLimit: numeric("customer_tf_limit", { precision: 10, scale: 2 }).default("0"),
    customerTsNominal: numeric("customer_ts_nominal", { precision: 10, scale: 2 }).default("0"),
    customerTsQty: numeric("customer_ts_qty", { precision: 10, scale: 2 }).default("0"),
    customerDepositStatus: enumBankStatusPajak("customer_deposit_status").default("rmi"),
    customerBisnisType: enumCustomerBisnisType("customer_bisnis_type").default("counter"),
    customerEbelanjaPoint: enumZeroOne("customer_ebelanja_point").default("0"),
    customerBlockDesc: text("customer_block_desc"),
    customerMarkupArea: enumZeroOne("customer_markup_area").default("1"),
    customerMinus: enumZeroOne("customer_minus").default("1"),
    customerOutlet: enumZeroOne("customer_outlet").default("0"),
    customerDepo: enumZeroOne("customer_depo").default("0"),
    customerWallet: enumZeroOne("customer_wallet").default("1"),
    customerGame: enumZeroOne("customer_game").default("0"),
    customerTfSaldo: enumCustomerTfSaldo("customer_tf_saldo").notNull().default("close"),
    customerTfUang: enumZeroOne("customer_tf_uang").default("0"),
    customerStatus: enumCustomerStatus("customer_status").default("new"),
    customerCreateDate: timestamp("customer_create_date", { withTimezone: true }),
  },
  (t) => ({
    cityIdx: index("_customer_customer_city").on(t.customerCity),
    codeIdx: index("_customer_customer_code").on(t.customerCode),
    createDateIdx: index("_customer_customer_create_date").on(t.customerCreateDate.desc()),
    ebelanjaPointIdx: index("_customer_customer_ebelanja_point").on(t.customerEbelanjaPoint),
    emailIdx: index("_customer_customer_email").on(t.customerEmail),
    levelIdx: index("_customer_customer_level").on(t.customerLevel),
    parentIdx: index("_customer_customer_parent").on(t.customerParent),
    phoneIdx: index("_customer_customer_phone").on(t.customerPhone),
    provinceIdx: index("_customer_customer_province").on(t.customerProvince),
    statusSingleIdx: index("_customer_customer_status").on(t.customerStatus),
    picIdIdx: index("_customer_pic_id").on(t.picId),
    statusComboIdx: index("_customer_status").on(
      t.customerLevel,
      t.customerCode,
      t.customerEmail,
      t.customerPhone,
      t.customerCity,
      t.customerProvince,
      t.customerEbelanjaPoint,
      t.customerStatus,
    ),
  }),
);

export type Customer = typeof customerTable.$inferSelect;
export type NewCustomer = typeof customerTable.$inferInsert;
