import { pgTable, bigint, varchar, text, timestamp, index, numeric } from "drizzle-orm/pg-core";
import {
  enumOrderPaymentType,
  enumOrderShipmentType,
  enumOrderShipmentCost,
  enumOrderStatus,
} from "./enums";

export const orderTable = pgTable(
  "_order",
  {
    orderId: bigint("order_id", { mode: "number" }).generatedAlwaysAsIdentity().primaryKey(),
    orderNumber: varchar("order_number", { length: 20 }),
    oPaymentId: bigint("o_payment_id", { mode: "number" }),
    customerId: bigint("customer_id", { mode: "number" }),
    merchantId: bigint("merchant_id", { mode: "number" }),
    driverId: bigint("driver_id", { mode: "number" }),
    orderShipmentType: enumOrderShipmentType("order_shipment_type").default("driver"),
    orderPaymentType: enumOrderPaymentType("order_payment_type").default("balance"),
    paymentMethodId: bigint("payment_method_id", { mode: "number" }),
    paymentMethodGroup: varchar("payment_method_group", { length: 50 }),
    paymentMethodName: varchar("payment_method_name", { length: 50 }),
    paymentMethodDesc: text("payment_method_desc"),
    orderSubtotal: numeric("order_subtotal", { precision: 10, scale: 2 }),
    orderTax: numeric("order_tax", { precision: 10, scale: 2 }),
    orderDiscountPrice: numeric("order_discount_price", { precision: 10, scale: 2 }),
    orderShipmentPrice: numeric("order_shipment_price", { precision: 10, scale: 2 }),
    orderShipmentDiscount: numeric("order_shipment_discount", { precision: 10, scale: 2 }).default(
      "0",
    ),
    orderInsurance: numeric("order_insurance", { precision: 10, scale: 2 }),
    orderAdmin3rdparty: numeric("order_admin_3rdparty", { precision: 10, scale: 2 }),
    orderTotal: numeric("order_total", { precision: 10, scale: 2 }),
    orderUniqueCode: bigint("order_unique_code", { mode: "number" }),
    orderBankFromAccount: varchar("order_bank_from_account", { length: 50 }),
    orderBankFromNumber: varchar("order_bank_from_number", { length: 50 }),
    orderBankFromBranch: varchar("order_bank_from_branch", { length: 50 }),
    orderShipmentCost: enumOrderShipmentCost("order_shipment_cost").default("merchant"),
    orderShipmentCourier: varchar("order_shipment_courier", { length: 255 }),
    orderShipmentPackage: varchar("order_shipment_package", { length: 255 }),
    orderShipmentTime: varchar("order_shipment_time", { length: 255 }),
    orderShipmentDate: timestamp("order_shipment_date", { withTimezone: true }),
    rCityId: bigint("r_city_id", { mode: "number" }),
    orderShipmentTo: varchar("order_shipment_to", { length: 50 }),
    orderShipmentAddress: text("order_shipment_address"),
    orderShipmentLat: varchar("order_shipment_lat", { length: 20 }),
    orderShipmentLng: varchar("order_shipment_lng", { length: 20 }),
    orderShipmentNote: text("order_shipment_note"),
    orderShipmentPhone: varchar("order_shipment_phone", { length: 20 }),
    orderShipmentResi: varchar("order_shipment_resi", { length: 255 }),
    orderStatus: enumOrderStatus("order_status"),
    orderPendingPaymentDate: timestamp("order_pending_payment_date", { withTimezone: true }),
    orderPendingPaymentNote: text("order_pending_payment_note"),
    orderPaidDate: timestamp("order_paid_date", { withTimezone: true }),
    orderPaidNote: text("order_paid_note"),
    orderProcessDate: timestamp("order_process_date", { withTimezone: true }),
    orderProcessNote: text("order_process_note"),
    orderPickupDate: timestamp("order_pickup_date", { withTimezone: true }),
    orderPickupNote: text("order_pickup_note"),
    orderFinishDate: timestamp("order_finish_date", { withTimezone: true }),
    orderFinishNote: text("order_finish_note"),
    orderCancelDate: timestamp("order_cancel_date", { withTimezone: true }),
    orderCancelNote: text("order_cancel_note"),
    orderRefundDate: timestamp("order_refund_date", { withTimezone: true }),
    orderRefundNote: text("order_refund_note"),
    orderCreateDate: timestamp("order_create_date", { withTimezone: true }),
  },
  (t) => ({
    amountIdx: index("_order_amount").on(t.orderSubtotal, t.orderShipmentPrice, t.orderTotal),
    customerIdIdx: index("_order_customer_id").on(t.customerId),
    driverIdIdx: index("_order_driver_id").on(t.driverId),
    idIdx: index("_order_id").on(t.oPaymentId, t.customerId, t.merchantId, t.rCityId),
    merchantIdIdx: index("_order_merchant_id").on(t.merchantId),
    numberIdx: index("_order_number").on(t.orderNumber),
    oPaymentIdIdx: index("_order_o_payment_id").on(t.oPaymentId),
    createDateIdx: index("_order_order_create_date").on(t.orderCreateDate),
    paymentTypeIdx: index("_order_order_payment_type").on(t.orderPaymentType),
    shipmentTypeIdx: index("_order_order_shipment_type").on(t.orderShipmentType),
    orderStatusIdx: index("_order_order_status").on(t.orderStatus),
    rCityIdIdx: index("_order_r_city_id").on(t.rCityId),
    statusIdx: index("_order_status").on(t.orderShipmentType, t.orderPaymentType, t.orderStatus),
  }),
);

export type Order = typeof orderTable.$inferSelect;
export type NewOrder = typeof orderTable.$inferInsert;
